#!/bin/bash

# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generate .env for video-analytics-api integration test Docker Compose.
# Usage: source generate_env.sh   (from test.sh or cleanup.sh)

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

SCRIPT_DIR="${SCRIPT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"

# Paths
INTEGRATION_TEST_DIR="$(cd "$SCRIPT_DIR" && pwd)"
# WEB_APIS_ROOT = directory containing docker/Dockerfile (repo root)
WEB_APIS_ROOT="$(cd "$INTEGRATION_TEST_DIR/.." && pwd)"
if [ ! -f "$WEB_APIS_ROOT/docker/Dockerfile" ]; then
    WEB_APIS_ROOT="$(cd "$INTEGRATION_TEST_DIR/../.." && pwd)"
fi
DATA_DIR="$INTEGRATION_TEST_DIR/docker_compose/apps_data"

# Host IP for any advertised listeners
if command -v ip >/dev/null 2>&1; then
    HOST_IP="$(ip route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}')"
fi
if [ -z "${HOST_IP:-}" ]; then
    HOST_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
fi
if [ -z "${HOST_IP:-}" ]; then
    HOST_IP="localhost"
fi

ENV_FILE="$SCRIPT_DIR/docker_compose/infra/.env"
echo "Generating environment at $ENV_FILE"

cat > "$ENV_FILE" << EOF
# Video analytics API integration test environment
# Generated by generate_env.sh on $(date)

export INTEGRATION_TEST_DIR=$INTEGRATION_TEST_DIR
export WEB_APIS_ROOT=$WEB_APIS_ROOT
export DATA_DIR=$DATA_DIR
export HOST_IP=$HOST_IP
export COMPOSE_PROJECT_NAME=video-analytics-api-integration
EOF

COMPOSE_PROJECT_NAME=video-analytics-api-integration
echo "Generated .env (COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME)"
